version: "2"
services:
  web:
    image: juliettet/front-end-react-prod-deploy_web:latest
    networks:
     - network
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./.certs:/etc/certs
    ports:
     - "443:443"
  redis:
    image: redis:alpine
    networks:
     - network
  api:
    image: juliettet/my-express-docker-prod-deploy_api:latest
    networks:
     - network
networks:
  network:


# Remove dangling volumes
# docker volume rm `docker volume ls -q -f dangling=true`
